version: '3'

services:
  elitedomashka:
    build: .
    container_name: "elitedomashka"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.basic.port=5000"
      - "traefik.frontend.rule=Host:backend.domashka.cloud"
    ports:
      - '${LARAVELS_LISTEN_PORT}:80'
    networks:
      - web
      - internal
#      - default
    depends_on:
      - db
      - redis

  db:
    image: "postgres"
    container_name: "postgres"
    labels:
      - "traefik.enable=false"
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - internal
    volumes:
      - dbdata:/var/lib/postgresql/data
#  adminer:
#    image: adminer
#    networks:
#      - internal
#      - web
#    ports:
#      - 8081:8080
#    depends_on:
#      - db
  redis:
    image: redis:5-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - internal
    volumes:
      - redis-data:/data
volumes:
  dbdata:
  redis-data:
networks:
  web:
    external: true
  internal:
    external: false
