version: '3'

services:
  elitedomashka:
    build: .
#    container_name: "elitedomashka"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.basic.port=${LARAVELS_LISTEN_PORT}"
      - "traefik.frontend.rule=Host:${APP_DOMAIN}"
    ports:
      - '${LARAVELS_LISTEN_PORT}'
#    volumes:
#      - /home/alexey/projects/newdomashka/backend:/var/www
    networks:
      - web
      - internal
#      - default
#    depends_on:
##      - db
#      - redis

  db:
    image: "postgres:12"
    container_name: "postgres"
    labels:
      - "traefik.enable=false"
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - internal
    volumes:
      - dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    labels:
      - "traefik.enable=false"
    networks:
      - internal
      - web
    ports:
      - 8081:8080
    depends_on:
      - db
  redis:
    image: redis:5-alpine
    labels:
      - "traefik.enable=false"
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--port", "${REDIS_PORT}"]
    hostname: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - internal
    volumes:
      - redis-data:/data
volumes:
  dbdata:
  redis-data:
networks:
  web:
    external: true
  internal:
    external: false
